### ISSUE TITLE
Crash when importing data of wrong filetype

### ISSUE THREAD

**Issue by carterbox** [AdvancedPhotonSource/ptychodus#32]
version 0.1.1.dev30+ga87b01e

I tried loading some velociprobe master file data, but I forgot to choose this filetype in the drop down. Instead, the generic HDF5 filetype was selected. This caused the entire program to crash with a division by zero error:

```
DEBUG:ptychodus.model.data:Reading /home/beams4/DCHING/Documents/ptychodus/test/fly001-20220218T180854Z-001/fly001/fly001_master.h5
DEBUG:ptychodus.model.data:Scratch memory is (0, 0, 0)
Traceback (most recent call last):
  File "/home/beams4/DCHING/Documents/ptychodus/ptychodus/controller/core.py", line 85, in <lambda>
    lambda checked: controller._dataFileController.openDataFile())
  File "/home/beams4/DCHING/Documents/ptychodus/ptychodus/controller/data.py", line 162, in openDataFile
    self._presenter.openDataFile(filePath, nameFilter)
  File "/home/beams4/DCHING/Documents/ptychodus/ptychodus/model/data.py", line 542, in openDataFile
    self._settings.filePath.value = filePath
  File "/home/beams4/DCHING/Documents/ptychodus/ptychodus/api/settings.py", line 34, in value
    self.notifyObservers()
  File "/home/beams4/DCHING/Documents/ptychodus/ptychodus/api/observer.py", line 29, in notifyObservers
    observer.update(self)
  File "/home/beams4/DCHING/Documents/ptychodus/ptychodus/model/data.py", line 553, in update
    self._openDataFileFromSettings()
  File "/home/beams4/DCHING/Documents/ptychodus/ptychodus/model/data.py", line 545, in _openDataFileFromSettings
    self._openDataFile(self._settings.filePath.value)
  File "/home/beams4/DCHING/Documents/ptychodus/ptychodus/model/data.py", line 534, in _openDataFile
    self._activeDataFile.setActive(dataFile)
  File "/home/beams4/DCHING/Documents/ptychodus/ptychodus/model/data.py", line 432, in setActive
    stride = int(dataFile.metadata.totalNumberOfImages) // len(dataFile)
ZeroDivisionError: integer division or modulo by zero
```
Probably, this error should be caught and the GUI should recover by notifying the user that the data is invalid.

**Comment by stevehenke** [comment]
Fixed in v0.2.0. Thank you for reporting this!
